In [1]:
import pandas as pd
import numpy as np

In [33]:
data = {'color' : ['blue','green','yellow','red','white'],
        'object' : ['ball','pen','pencil','paper','mug'],
        'price' : [1.2,1.0,0.6,0.9,1.7]}

In [34]:
df = pd.DataFrame(data)
df

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [3]:
df = pd.DataFrame(data, columns = ['color', 'price'])
df

color  price
0    blue    1.2
1   green    1.0
2  yellow    0.6
3     red    0.9
4   white    1.7

In [6]:
df = pd.DataFrame(data, columns = ['object', 'price'], index = ['uno','dos','tres','cuatro','cinco'])
df

object  price
uno       ball    1.2
dos        pen    1.0
tres    pencil    0.6
cuatro   paper    0.9
cinco      mug    1.7

In [7]:
df.loc['uno']

object    ball
price      1.2
Name: uno, dtype: object

In [20]:
df[['object','price']]

object  price
uno       ball    1.2
dos        pen    1.0
tres    pencil    0.6
cuatro   paper    0.9
cinco      mug    1.7

In [14]:
df.price.object

AttributeError: 'Series' object has no attribute 'object'

In [13]:
df.sum()

object    ballpenpencilpapermug
price                       5.4
dtype: object

In [18]:
df['price']['uno']

1.2

In [21]:
df.iloc[0,1]

1.2

In [23]:
df.iloc[2:4,]

object  price
tres    pencil    0.6
cuatro   paper    0.9

In [24]:
df.iloc[2:4,-1]

tres      0.6
cuatro    0.9
Name: price, dtype: float64

In [29]:
df.reset_index(drop = True, inplace = True)

In [30]:
df

object  price
0    ball    1.2
1     pen    1.0
2  pencil    0.6
3   paper    0.9
4     mug    1.7

In [32]:
df_2 = pd.DataFrame(np.arange(16).reshape((4,4)),
                                           index = ['red','blue','yellow','white'],
                                           columns = ['ball','pen','pencil','paper'])

In [36]:
df_2

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [40]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
df_2['nueva_col'] = 'dato'
df_2

ball  pen  pencil  paper nueva_col
red        0    1       2      3      dato
blue       4    5       6      7      dato
yellow     8    9      10     11      dato
white     12   13      14     15      dato

In [43]:
df_2['col4'] = df_2['pen']/2
df_2

ball  pen  pencil  paper nueva_col  col4
red        0    1       2      3      dato   0.5
blue       4    5       6      7      dato   2.5
yellow     8    9      10     11      dato   4.5
white     12   13      14     15      dato   6.5

In [44]:
df_2['nueva_col'] = [i for i in range(len(df_2))]

In [45]:
df_2

ball  pen  pencil  paper  nueva_col  col4
red        0    1       2      3          0   0.5
blue       4    5       6      7          1   2.5
yellow     8    9      10     11          2   4.5
white     12   13      14     15          3   6.5

In [49]:
df_2.drop('paper', axis = 1, inplace = True)

In [51]:
df_2.drop(['nueva_col', 'col4'], axis = 1, inplace = True)

In [52]:
df_2

ball  pen  pencil
red        0    1       2
blue       4    5       6
yellow     8    9      10
white     12   13      14

In [54]:
df_2.drop('white', inplace = True)

In [55]:
df_2

ball  pen  pencil
red        0    1       2
blue       4    5       6
yellow     8    9      10

In [57]:
df_2.loc['yellow','pencil'] = 20

In [58]:
df_2

ball  pen  pencil
red        0    1       2
blue       4    5       6
yellow     8    9      20

In [60]:
df_2.replace(20,11, inplace = True)

In [62]:
df_2['ball_2'] = df_2['ball'] 

In [64]:
df_2.replace(8,5)

ball  pen  pencil  ball_2
red        0    1       2       0
blue       4    5       6       4
yellow     5    9      11       5

In [66]:
df_2.loc['yellow','pencil']

11

In [67]:
df_2.at['yellow','pencil']

11

In [69]:
df_2.rename(columns = {'pen':'pen_2'}, inplace = True)
df_2

ball  pen_2  pencil  ball_2
red        0      1       2       0
blue       4      5       6       4
yellow     8      9      11       8

In [74]:
df_2.columns = ['ball2','pen3','pencil2','paper2']

In [75]:
df_2

ball2  pen3  pencil2  paper2
red         0     1        2       0
blue        4     5        6       4
yellow      8     9       11       8

In [76]:
df_2/2

ball2  pen3  pencil2  paper2
red       0.0   0.5      1.0     0.0
blue      2.0   2.5      3.0     2.0
yellow    4.0   4.5      5.5     4.0

In [78]:
df_2['str_ball'] = str(df_2['ball2'])

In [80]:
df_2/2

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [81]:
df_2.drop('str_ball', axis =1 ,inplace = True)

In [82]:
df_2

ball2  pen3  pencil2  paper2
red         0     1        2       0
blue        4     5        6       4
yellow      8     9       11       8

In [83]:
np.sqrt(df_2)

ball2      pen3   pencil2    paper2
red     0.000000  1.000000  1.414214  0.000000
blue    2.000000  2.236068  2.449490  2.000000
yellow  2.828427  3.000000  3.316625  2.828427

In [84]:
f = lambda x: x.max() - x.min()

In [85]:
df_2.apply(f) #por defecto apply trabaja sobre filas

ball2      8
pen3       8
pencil2    9
paper2     8
dtype: int64

In [88]:
df_2.apply(f, axis = 1) #axis trabaja sobre columnas

red       2
blue      2
yellow    3
dtype: int64

In [89]:
df_2

ball2  pen3  pencil2  paper2
red         0     1        2       0
blue        4     5        6       4
yellow      8     9       11       8

In [91]:
f_2 = lambda x: x+1

In [92]:
df_2['ball2'].apply(f_2)

red       1
blue      5
yellow    9
Name: ball2, dtype: int64

In [93]:
def f_3(x):
    return pd.Series([x.min(),x.max()], index = ['min','max'])
    

In [97]:
df_2

ball2  pen3  pencil2  paper2
red         0     1        2       0
blue        4     5        6       4
yellow      8     9       11       8

In [96]:
df_2.apply(f_3)

ball2  pen3  pencil2  paper2
min      0     1        2       0
max      8     9       11       8

In [98]:
df_2.apply(f_3, axis = 1)

min  max
red       0    2
blue      4    6
yellow    8   11

In [101]:
df_2.sum()

ball2      12
pen3       15
pencil2    19
paper2     12
dtype: int64

In [102]:
df_2.sum(axis = 1)

red        3
blue      19
yellow    36
dtype: int64

In [103]:
df_2.mean()

ball2      4.000000
pen3       5.000000
pencil2    6.333333
paper2     4.000000
dtype: float64

In [104]:
df_2.mean(axis = 1)

red       0.75
blue      4.75
yellow    9.00
dtype: float64

In [105]:
df_2.describe()

ball2  pen3    pencil2  paper2
count    3.0   3.0   3.000000     3.0
mean     4.0   5.0   6.333333     4.0
std      4.0   4.0   4.509250     4.0
min      0.0   1.0   2.000000     0.0
25%      2.0   3.0   4.000000     2.0
50%      4.0   5.0   6.000000     4.0
75%      6.0   7.0   8.500000     6.0
max      8.0   9.0  11.000000     8.0

In [112]:
df_2.sort_values(by = ['pen3','pencil2'], ascending = False)

ball2  pen3  pencil2  paper2
yellow      8     9       11       8
blue        4     5        6       4
red         0     1        2       0

In [114]:
df_2.sort_index(ascending = False)

ball2  pen3  pencil2  paper2
yellow      8     9       11       8
red         0     1        2       0
blue        4     5        6       4

In [127]:
ser = pd.Series([0,np.NaN,2,np.NaN,9],
                index=['red','blue','yellow','white','green'])

In [124]:
ser[ser.notnull()]

red       0.0
yellow    2.0
green     9.0
dtype: float64

In [125]:
ser.fillna('Este valor no esta disponible', inplace = True)

In [126]:
ser

red                                   0
blue      Este valor no esta disponible
yellow                                2
white     Este valor no esta disponible
green                                 9
dtype: object

In [130]:
ser.dropna(inplace = True)

In [131]:
ser = pd.Series([0,np.NaN,2,np.NaN,9],
                index=['red','blue','yellow','white','green'])

In [133]:
ser.isnull()

red       False
blue       True
yellow    False
white      True
green     False
dtype: bool

In [134]:
ser.isna()

red       False
blue       True
yellow    False
white      True
green     False
dtype: bool

In [135]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, red to yellow
Data columns (total 4 columns):
ball2      3 non-null int32
pen3       3 non-null int32
pencil2    3 non-null int32
paper2     3 non-null int32
dtypes: int32(4)
memory usage: 152.0+ bytes


In [137]:
mser = pd.Series(np.random.rand(8),index=[['white','white','white','blue','blue','red','red','red'],
                        ['up','down','right','up','down','up','down','left']])

In [138]:
mser

white  up       0.917853
       down     0.566584
       right    0.752167
blue   up       0.738369
       down     0.298148
red    up       0.954547
       down     0.586443
       left     0.537330
dtype: float64

In [140]:
mser['white']['right']

0.7521671897163755

In [141]:
mser[:,'up']

white    0.917853
blue     0.738369
red      0.954547
dtype: float64

In [142]:
mser[:,'left']

red    0.53733
dtype: float64

In [145]:
mser.unstack()

down     left     right        up
blue   0.298148      NaN       NaN  0.738369
red    0.586443  0.53733       NaN  0.954547
white  0.566584      NaN  0.752167  0.917853

In [149]:
frame5 = pd.read_csv('data/ex6.csv', 
                     header = None,
                     names = ['col1','col2','col3','col4','col5'],
                    nrows= 3)

In [150]:
frame5

col1  col2  col3  col4   col5
0     1     5     2     3    cat
1     2     7     8     5    dog
2     3     3     6     7  horse

In [151]:
frame7 = pd.read_csv('data/ex7.csv', index_col = ['color','status'])
frame7

item1  item2  item3
color status                     
black up          3      4      6
      down        2      6      7
white up          5      5      5
      down        3      3      2
      left        1      2      1
red   up          2      2      2
      down        1      1      4

In [152]:
frame7.unstack()

item1           item2           item3          
status  down left   up  down left   up  down left   up
color                                                 
black    2.0  NaN  3.0   6.0  NaN  4.0   7.0  NaN  6.0
red      1.0  NaN  2.0   1.0  NaN  2.0   4.0  NaN  2.0
white    3.0  1.0  5.0   3.0  2.0  5.0   2.0  1.0  5.0

In [153]:
pd.read_table('data/ex8.txt', sep = '\D+', header = None)

C:\Users\GralG\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


0    1    2
0  0  123  122
1  1  124  321
2  2  125  333

In [154]:
pd.read_excel('data/data.xlsx', index_col = 0, sheet_name = 'hoja1')

white  red  green  black
a     12   23     17     18
b     22   16     19     18
c     14   23     22     21

In [156]:
hoja2 = pd.read_excel('data/data.xlsx', index_col = 0, sheet_name = 'hoja2')
hoja2

yellow  purple  blue  orange
A      11      16    44   22.00
B      20      22    23   44.00
C      30      31    37    0.32

In [157]:
hoja2.to_excel('data/data2.xlsx')

In [159]:
hoja2.to_html('data/data2.html')

In [160]:
s = ['<HTML>']
s.append('<HEAD><TITLE> My dataframe </TITLE></HEAD>')
s.append('<BODY>')
s.append(hoja2.to_html())
s.append('</BODY></HTML>')
html = ''.join(s)

In [163]:
print(html)

<HTML><HEAD><TITLE> My dataframe </TITLE></HEAD><BODY><table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>yellow</th>
      <th>purple</th>
      <th>blue</th>
      <th>orange</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>A</th>
      <td>11</td>
      <td>16</td>
      <td>44</td>
      <td>22.00</td>
    </tr>
    <tr>
      <th>B</th>
      <td>20</td>
      <td>22</td>
      <td>23</td>
      <td>44.00</td>
    </tr>
    <tr>
      <th>C</th>
      <td>30</td>
      <td>31</td>
      <td>37</td>
      <td>0.32</td>
    </tr>
  </tbody>
</table></BODY></HTML>


In [164]:
html_file = open('data/mydata.html','w') #Abriendo archivo listo para escribir

In [166]:
html_file.write(html) #Escribiendo mi variable html en el archivo abierto

635

In [167]:
html_file.close()

In [168]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'price': [12.33,11.44,33.21,13.23,33.62]})
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'color': ['white','red','red','black']})

In [169]:
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [170]:
frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [171]:
pd.merge(frame1,frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [172]:
pd.merge(frame1,frame2, how = 'left')

id  price  color
0     ball  12.33    red
1   pencil  11.44  white
2   pencil  11.44    red
3      pen  33.21  black
4      mug  13.23    NaN
5  ashtray  33.62    NaN

In [177]:
pd.merge(frame2,frame1, how = 'right')

id  color  price
0   pencil  white  11.44
1   pencil    red  11.44
2     ball    red  12.33
3      pen  black  33.21
4      mug    NaN  13.23
5  ashtray    NaN  33.62

In [176]:
pd.merge(frame2,frame1, how = 'left')

id  color  price
0  pencil  white  11.44
1  pencil    red  11.44
2    ball    red  12.33
3     pen  black  33.21

In [178]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                         'color': ['white','red','red','black','green'],
                         'brand': ['OMG','ABC','ABC','POD','POD']})

In [179]:
frame2 = pd.DataFrame({'id':['pencil','pencil','ball','pen'],
                        'brand': ['OMG','POD','ABC','POD']})

In [180]:
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [181]:
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [183]:
pd.merge(frame1,frame2, on = 'id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [184]:
pd.merge(frame1,frame2, on = 'brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

In [187]:
pd.merge(frame1,frame2, on = 'brand', how = 'right')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4  ashtray  green   POD  pencil
5      mug  black   POD     pen
6  ashtray  green   POD     pen

In [189]:
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [190]:
frame2.columns = ['brand','id']
frame2

brand   id
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [191]:
pd.merge(frame1, frame2, left_on = 'brand', right_on = 'id')

id_x  color brand_x brand_y id_y
0     ball  white     OMG  pencil  OMG
1   pencil    red     ABC    ball  ABC
2      pen    red     ABC    ball  ABC
3      mug  black     POD  pencil  POD
4      mug  black     POD     pen  POD
5  ashtray  green     POD  pencil  POD
6  ashtray  green     POD     pen  POD

In [194]:
pd.merge(frame1,frame2, on = 'id',how = 'outer')

id  color brand_x brand_y
0     ball  white     OMG     NaN
1   pencil    red     ABC     NaN
2      pen    red     ABC     NaN
3      mug  black     POD     NaN
4  ashtray  green     POD     NaN
5      OMG    NaN     NaN  pencil
6      POD    NaN     NaN  pencil
7      POD    NaN     NaN     pen
8      ABC    NaN     NaN    ball

In [195]:
array = np.arange(9).reshape((3,3))
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [196]:
array2 = np.arange(9).reshape((3,3))+6
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [197]:
np.concatenate([array,array2])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [198]:
np.concatenate([array,array2], axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [199]:
ser1 = pd.Series(np.random.rand(4), index = [1,2,3,4])
ser2 = pd.Series(np.random.rand(4), index = [5,6,7,8])
ser3 = pd.Series(np.random.rand(4), index = [1,2,3,4])

In [200]:
pd.concat([ser1,ser2,ser3])

1    0.260789
2    0.181214
3    0.001783
4    0.267834
5    0.607570
6    0.801559
7    0.792799
8    0.516152
1    0.042696
2    0.733170
3    0.592682
4    0.787912
dtype: float64

In [201]:
pd.concat([ser1,ser2,ser3], axis = 1)

0         1         2
1  0.260789       NaN  0.042696
2  0.181214       NaN  0.733170
3  0.001783       NaN  0.592682
4  0.267834       NaN  0.787912
5       NaN  0.607570       NaN
6       NaN  0.801559       NaN
7       NaN  0.792799       NaN
8       NaN  0.516152       NaN

In [202]:
pd.concat([ser1,ser3], axis = 1)

0         1
1  0.260789  0.042696
2  0.181214  0.733170
3  0.001783  0.592682
4  0.267834  0.787912